.PHONY: clean All

All:
	@echo "----------Building project:[ mypriority - Debug ]----------"
	@cd "mypriority" && $(MAKE) -f  "mypriority.mk"
clean:
	@echo "----------Cleaning project:[ mypriority - Debug ]----------"
	@cd "mypriority" && $(MAKE) -f  "mypriority.mk" clean
