all:
	g++ -o L5R L5RBlackCard.cpp L5RCard.cpp L5RDeckBuilder.cpp L5RFollower.cpp L5RGameBoard.cpp L5RGreenCard.cpp L5RHolding.cpp L5RItem.cpp L5RPersonality.cpp L5RPlayer.cpp L5RStronghold.cpp L5RTypeConverter.cpp L5RProvince.cpp main.cpp 

