.PHONY: clean All

All:
	@echo "----------Building project:[ remoteClient - Debug ]----------"
	@$(MAKE) -f  "remoteClient.mk"
clean:
	@echo "----------Cleaning project:[ remoteClient - Debug ]----------"
	@$(MAKE) -f  "remoteClient.mk" clean
