.PHONY: clean All

All:
	@echo "----------Building project:[ dataServer - Debug ]----------"
	@$(MAKE) -f  "dataServer.mk"
clean:
	@echo "----------Cleaning project:[ dataServer - Debug ]----------"
	@$(MAKE) -f  "dataServer.mk" clean
