.PHONY: clean All

All:
	@echo "----------Building project:[ jobCommander - Debug ]----------"
	@$(MAKE) -f  "jobCommander.mk"
clean:
	@echo "----------Cleaning project:[ jobCommander - Debug ]----------"
	@$(MAKE) -f  "jobCommander.mk" clean
