.PHONY: clean All

All:
	@echo "----------Building project:[ jobExecutor - Debug ]----------"
	@$(MAKE) -f  "jobExecutor.mk"
clean:
	@echo "----------Cleaning project:[ jobExecutor - Debug ]----------"
	@$(MAKE) -f  "jobExecutor.mk" clean
