.PHONY: clean All

All:
	@echo "----------Building project:[ Ex2 - Debug ]----------"
	@cd "Ex2" && $(MAKE) -f  "Ex2.mk"
clean:
	@echo "----------Cleaning project:[ Ex2 - Debug ]----------"
	@cd "Ex2" && $(MAKE) -f  "Ex2.mk" clean
