.PHONY: clean All

All:
	@echo "----------Building project:[ Ex1 - Release ]----------"
	@cd "Ex1" && $(MAKE) -f  "Ex1.mk"
clean:
	@echo "----------Cleaning project:[ Ex1 - Release ]----------"
	@cd "Ex1" && $(MAKE) -f  "Ex1.mk" clean
